### ISSUE TITLE
Explicitly review importance of Quality Scenarios

### ISSUE THREAD

**Issue by aheusingfeld** [isaqb-org/curriculum-flex#17]
In the trainings attendees are very often surprised that their decisions e.g. for/against splitting a domain, picking a technology, making something a macro or micro architecture decision is supposed to be justified by referring to which Quality Goal (or scenario) this decision aims to fulfill. Thus we should explicitly request to stress this in certain parts of the curriculum

**Comment by svenjohann** [comment]
I like the idea. Maybe we can look at "architecture principles" as well. Those are driven by strategic business goals and risks. They are therefore related to the elevator mentioned in #20. Especially if you have many teams, it is hard to communicate the main business drives in a good manner so that architectural requirements and decisions can derived from them. 

Good source:  https://www.case-podcast.org/34-birgitta-bockeler-on-cultivating-architecture-principles :-)

Having those, it is always possible to trace a local (or global) architecture decision to a requirement and then to a business goal. You can vice versa show how a business goal or risk is addressed.

**Comment by aheusingfeld** [comment]
Done with #74
