### ISSUE TITLE
sub-title "Microservices and Self-Contained Systems" is no longer quite appropriate

### ISSUE THREAD

**Issue by sippsack** [isaqb-org/curriculum-flex#34]
It was certainly a good idea 8 years ago. It is still one of the solution approaches, but there are many more important aspects. Possible alternatives could be to name relevant quality characteristics such as scalability, extensibility, etc.

**Comment by aheusingfeld** [comment]
100% agreed, Falk. FLEX is 
1. about learning how to read your _context_ in order to take good decisions on modularization and 
2. about learning how to implement and deal with the impact of your modularization decisions

Thus "FLEX - modularization for flexibility, speed and resilience" might be a better title

**Comment by programming-wolf** [comment]
Then.. just do it? 🙂

**Comment by mrtnlhmnn** [comment]
I agree with the idea, makes absolutely sense to me. But I strongly suggest not to change this in this patch release 2024.1.
A lot of participants associate this training with the idea of Microservices, so I would not change this too "ad-hoc". 

Is IMHO too much of a "breaking change". 

Proposal: Do not delete the sub-title but make it less strict (perhaps in German: "Flexible Architekturmodell u.a. mit Microservices...")

**Comment by aheusingfeld** [comment]
fixed with d139a9f07f0b9f4c78eba756dcea841d9f3d9ecb
