### ISSUE TITLE
topics to be deleted in the curriculum

### ISSUE THREAD

**Issue by mrtnlhmnn** [isaqb-org/curriculum-flex#48]
The current topics of the curriculum should be skipped:

f) 12-factor app
g) Chapter 3 - "Datenfluss- und Batch-orientierte Systeme" (last bullet point on page 11)
h) Chapter 5 - "Die Teilnehmer sollen auf Basis des DevOps-Organisationsmodells einen Team-Aufbau skizzieren können". This is too ambitious, taking this learning goal literally. "Team-Aufbau" would need to take organizational requirements and team topologies into account. This goes too far for such a training.

**Comment by aburmeis** [comment]
Not sure about _f) 12-factor app_, but you have my go for _g)_ and _h)_. Btw. what about _OSGi Bundles_?

**Comment by mrtnlhmnn** [comment]
> what about OSGi Bundles?
Are you suggesting to skip these as well? 

Actually I would like to keep them. Yes, they are not very widespread and in business applications they typically don't play a role. But in embedded systems or "systems closer to hardware" , they are still well known. 
Especially when one needs 
a) strict encapsulation (ok, now also available with Java Jigsaw / JPMS, with lots of limitations) 
and/or b) lifecycle , i.e. the possibility to start/stop/pause/resume the bundles at runtime.

**Comment by aheusingfeld** [comment]
Interesting discussion here, I'm of exactly the opposite opinion: it turned out to actually be a very good practice every time I conduct the h) excercise because it makes participants think about the impact that code structure has on collaboration between teams and thus coordination effort which is the most common reason for coupling-issues in distributed systems.
